"""Phase 6 Plan 06-02: unified standard-layer corpus integration.

Merges the Kaggle standard corpus (regenerated by Plan 06-01 to
``data/standard/kaggle/{race,entry,result}.parquet``) with the scraped standard
partitions (``data/standard/scraped/{YYYYMM}/{race,entry,result}.parquet``) into
a single unified ``data/standard/{race,entry,result}.parquet`` corpus per
CONTEXT.md D-03/D-04.

The integration is **idempotent** (HIGH #5): Kaggle is read from a SEPARATE
input path (``kaggle_input_dir``, default ``standard_dir / 'kaggle'``) that is
NEVER the output path. A second invocation against the same immutable inputs
produces byte-identical output. This makes the validate-before-swap
transactionality model below fully recoverable -- a mid-swap crash leaves at
worst a partial swap, but re-running ``integrate_standard_layer`` restores a
consistent corpus because the transform is deterministic and reads only from
its immutable inputs.

Transactionality model (HIGH #6 cycle-3 + cycle-5):
    1. Build all 3 merged DataFrames in memory.
    2. Validate integrity via ``validate_integrity`` (HIGH #8) and the
       extended hard-violation filter (HIGH #8b cycle-4).
    3. Stage all 3 to a per-run ``tempfile.mkdtemp`` directory via
       ``_atomic_write_parquet``.
    4. Validate each staged file (row count > 0, schema column-set, PK unique).
    5. Swap each staged file into root via ``_commit_staging`` (DEDICATED
       module-level function -- cycle-5). The swap is wrapped in try/finally
       that best-effort-removes the staging dir.

The 3 sequential ``os.replace`` calls INSIDE ``_commit_staging`` are not
perfectly atomic; a failure between the 2nd and 3rd swap leaves a partial swap.
However, because integration is idempotent (reads only from immutable inputs),
re-running ``integrate_standard_layer`` against the same inputs reproduces
identical output and fully recovers. This is the genuinely correct guarantee
for a deterministic transform -- more robust than backup-and-restore (which
depends on the backup surviving the crash).

Hard-violation filter (HIGH #8b cycle-4):
    ``validate_integrity`` returns the entry/result 1-to-1 mismatch violation
    as ``"horse_race_id mismatch: entry/result are not 1-to-1 ..."`` which
    contains NEITHER ``"duplicate"`` NOR ``"orphan"``. The Phase 4
    ``normalizer.py`` token filter therefore misses it. This module EXTENDS
    the filter to also match ``"mismatch"`` and ``"1-to-1"`` (belt-and-braces
    -- either substring matches the violation string), so a structurally
    inconsistent entry/result corpus is never silently written.

Load-bearing anti-patterns (Pitfalls from 06-RESEARCH.md / 06-PATTERNS.md):
    - Pitfall 5: SCHEMA_BY_TABLE is HARDCODED as {race, entry, result}; do NOT
      iterate ``TABLE_TO_SCHEMA.keys()`` (that superset includes the Phase 5
      tables excluded from the unified corpus per D-05).
    - Pitfall 6: pre-dedup overlap RAISES (not silent ``drop_duplicates``).
    - D-05: never add a ``source`` column (rows must be indistinguishable).
    - loguru per-TABLE logging only (MEMORY.md scraper-logging-no-per-item).
"""

from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path

import pandas as pd
from loguru import logger
from pydantic import BaseModel

from src.schemas.audit import audit_leakage
from src.schemas.entry import EntrySchema
from src.schemas.race import RaceSchema
from src.schemas.result import ResultSchema
from src.scraper.normalizer import (
    _atomic_write_parquet,
    recast_to_canonical,
    validate_integrity,
)

# ---------------------------------------------------------------------------
# 3-table allowlist (Pitfall 5 / D-05 Phase-5-table protection)
# ---------------------------------------------------------------------------

#: Hardcoded 3-table allowlist. The Phase 5 tables (excluded from the unified
#: corpus per D-05) are deliberately NOT in this map; iterating
#: ``TABLE_TO_SCHEMA.keys()`` instead would overwrite the Phase 5 seed.
SCHEMA_BY_TABLE: dict[str, type[BaseModel]] = {
    "race": RaceSchema,
    "entry": EntrySchema,
    "result": ResultSchema,
}

#: Primary key per table. Used for pre-dedup overlap assertion (Pitfall 6).
PK_BY_TABLE: dict[str, str] = {
    "race": "race_id",
    "entry": "horse_race_id",
    "result": "horse_race_id",
}


# ---------------------------------------------------------------------------
# Helpers (reused from Phase 4 normalizer, NOT reimplemented)
#

# WR-04 (Phase 06 review): the local ``_recast_to_canonical`` definition was
# REMOVED in favor of the shared ``recast_to_canonical`` imported from
# ``src.scraper.normalizer``. The shared implementation uses COPY semantics
# (returns a new frame), which is the load-bearing behavior here: the callers
# at lines 285-286 invoke it on kaggle_df / scraped_df and rely on the
# originals being preserved for the audit call later. The back-compat alias
# keeps the underscore-prefixed name so existing references (and the
# ``__all__`` export) keep working.
# ---------------------------------------------------------------------------

_recast_to_canonical = recast_to_canonical


def _assert_column_set_equality(
    df: pd.DataFrame, schema: type[BaseModel], source_label: str
) -> None:
    """HIGH #9: column-set equality assert BEFORE reindex.

    ``pd.concat`` aligns on column names but takes the UNION of column sets,
    silently inflating the schema if one frame has an extra/dropped/renamed
    column. This guard refuses to reindex a frame whose column set diverges
    from ``schema.model_fields`` so the union can never silently grow.
    """
    expected = set(schema.model_fields.keys())
    actual = set(df.columns)
    if actual != expected:
        extra = actual - expected
        missing = expected - actual
        raise ValueError(
            f"{source_label}: column set mismatch "
            f"(extra={sorted(extra)}, missing={sorted(missing)}); "
            f"refusing to reindex"
        )


def _commit_staging(staging_dir: Path, standard_dir: Path) -> None:
    """Atomically-ish swap each staged table into the standard root.

    Performs exactly 3 ``os.replace`` calls (one per table in
    ``SCHEMA_BY_TABLE`` order). This function exists as a SEPARATE, PATCHABLE
    boundary so the transactionality regression test
    (``test_integration_partial_swap_recoverable``) can inject a mid-swap
    failure by monkeypatching THIS symbol -- NOT global ``os.replace``, which
    is also called by ``_atomic_write_parquet`` during the staging WRITES and
    would fire the monkeypatch at the wrong stage (cycle-4 NEW HIGH #2 fix).

    The 3 swaps are sequential, not atomic as a group. A failure between the
    2nd and 3rd swap leaves a partial swap (race swapped, entry/result not).
    Recovery is via idempotent re-run of ``integrate_standard_layer`` (HIGH #5
    + HIGH #6): the transform reads only from immutable inputs
    (``data/standard/kaggle/`` + scraped partitions), so re-running produces
    byte-identical output that fully restores the corpus.
    """
    for table in ("race", "entry", "result"):
        os.replace(
            staging_dir / f"{table}.parquet",
            standard_dir / f"{table}.parquet",
        )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def integrate_standard_layer(
    standard_dir: Path = Path("data/standard"),
    kaggle_input_dir: Path | None = None,
) -> dict:
    """Merge Kaggle + scraped corpora into a unified standard-layer corpus.

    Parameters
    ----------
    standard_dir : pathlib.Path, default ``Path("data/standard")``
        Root standard directory. The output ``race``/``entry``/``result``
        Parquet are written here (D-03 -- overwrite, table-per-file per D-04).
        Scraped partitions are read from ``standard_dir / "scraped"``.
    kaggle_input_dir : pathlib.Path, optional
        SEPARATE Kaggle input path (HIGH #5 idempotency). Defaults to
        ``standard_dir / "kaggle"``. NEVER reads Kaggle from the output path.

    Returns
    -------
    dict
        ``{"race": Path, "entry": Path, "result": Path, "audit": {...}}``.
        The ``audit`` sub-dict records ``audit_leakage`` results per table.

    Raises
    ------
    FileNotFoundError
        If any Kaggle input Parquet is missing, or a scraped month directory
        lacks one of the 3 expected table files (MEDIUM #14).
    ValueError
        If ``standard_dir / "scraped"`` is absent or contains zero month
        directories (MEDIUM #14); on pre-dedup PK overlap (Pitfall 6); on
        column-set mismatch before reindex (HIGH #9); on hard integrity
        violations -- duplicate PK, FK orphan, OR entry/result horse_race_id
        1-to-1 mismatch (HIGH #8b cycle-4); on unexpected audit leakage.
    TypeError
        If a column cannot be coerced to its target dtype during recast.

    Notes
    -----
    The transform is IDEMPOTENT (HIGH #5). Kaggle is read from
    ``kaggle_input_dir`` (a stable separate input); scraped partitions are
    immutable inputs. A second invocation against the same inputs produces
    byte-identical output, fully recovering from any partial swap left by a
    mid-swap crash (HIGH #6 validate-before-swap with idempotent recovery via
    the DEDICATED ``_commit_staging`` swap function).
    """
    standard_dir = Path(standard_dir)
    if kaggle_input_dir is None:
        kaggle_input_dir = standard_dir / "kaggle"
    kaggle_input_dir = Path(kaggle_input_dir)

    logger.info(
        f"integrate_standard_layer: starting "
        f"(standard_dir={standard_dir!s}, kaggle_input_dir={kaggle_input_dir!s})"
    )

    # ----- MEDIUM #14: validate scraped input exists with >=1 month -----
    scraped_root = standard_dir / "scraped"
    if not scraped_root.exists():
        raise ValueError(
            f"integrate_standard_layer: scraped root {scraped_root!s} does not "
            f"exist; integration requires at least one scraped month partition"
        )
    month_dirs = sorted(p for p in scraped_root.iterdir() if p.is_dir())
    if not month_dirs:
        raise ValueError(
            f"integrate_standard_layer: scraped root {scraped_root!s} contains "
            f"zero month directories; integration requires scraped data"
        )

    # ----- Build merged frames per table -----
    merged_by_table: dict[str, pd.DataFrame] = {}

    for table, schema in SCHEMA_BY_TABLE.items():
        pk = PK_BY_TABLE[table]
        canonical_cols = list(schema.model_fields.keys())

        # HIGH #5: Kaggle read from SEPARATE input path, NOT output path.
        kaggle_path = kaggle_input_dir / f"{table}.parquet"
        if not kaggle_path.exists():
            raise FileNotFoundError(
                f"integrate_standard_layer: Kaggle input missing: {kaggle_path!s} "
                f"(table={table!r})"
            )
        kaggle_df = pd.read_parquet(kaggle_path, engine="pyarrow")

        # MEDIUM #14: per-month table file must exist.
        scraped_dfs: list[pd.DataFrame] = []
        for month_dir in month_dirs:
            month_table_path = month_dir / f"{table}.parquet"
            if not month_table_path.exists():
                raise FileNotFoundError(
                    f"integrate_standard_layer: scraped month {month_dir.name!r} "
                    f"lacks {table!r}.parquet at {month_table_path!s}"
                )
            scraped_dfs.append(pd.read_parquet(month_table_path, engine="pyarrow"))
        scraped_df = pd.concat(scraped_dfs, ignore_index=True) if scraped_dfs else pd.DataFrame(
            columns=canonical_cols
        )

        # HIGH #9: column-set equality BEFORE reindex.
        _assert_column_set_equality(kaggle_df, schema, f"kaggle[{table!r}]")
        _assert_column_set_equality(scraped_df, schema, f"scraped[{table!r}]")

        # Reindex to canonical column order, then recast to SCHEMA_DTYPE_MAP.
        kaggle_df = kaggle_df.reindex(columns=canonical_cols)
        scraped_df = scraped_df.reindex(columns=canonical_cols)
        kaggle_df = _recast_to_canonical(kaggle_df, schema)
        scraped_df = _recast_to_canonical(scraped_df, schema)

        merged = pd.concat([kaggle_df, scraped_df], ignore_index=True)

        # Pitfall 6: pre-dedup overlap RAISES (not silent drop_duplicates).
        if pk in merged.columns:
            dup_count = int(merged[pk].duplicated().sum())
            if dup_count > 0:
                overlapping = (
                    merged.loc[merged[pk].duplicated(keep=False), pk]
                    .dropna()
                    .unique()[:5]
                    .tolist()
                )
                raise ValueError(
                    f"integrate_standard_layer[{table!r}]: {dup_count} duplicate "
                    f"{pk!r} values post-concat -- unexpected Kaggle/scraped "
                    f"overlap; sample={overlapping}"
                )

        merged_by_table[table] = merged
        logger.info(
            f"integrate_standard_layer[{table!r}]: merged "
            f"{len(kaggle_df)} kaggle + {len(scraped_df)} scraped = "
            f"{len(merged)} rows"
        )

    merged_race = merged_by_table["race"]
    merged_entry = merged_by_table["entry"]
    merged_result = merged_by_table["result"]

    # ----- HIGH #8 + HIGH #8b cycle-4: validate_integrity + extended filter -----
    violations = validate_integrity(merged_race, merged_entry, merged_result)
    if violations:
        logger.warning(
            f"integrate_standard_layer: {len(violations)} integrity violation(s) "
            f"detected (hard violations raise below)"
        )
    # HIGH #8b: extended token set -- 'mismatch'/'1-to-1' catch the
    # 'horse_race_id mismatch: entry/result are not 1-to-1' violation string
    # at normalizer.py:330-334 which contains NEITHER 'duplicate' NOR 'orphan'.
    hard_violations = [
        v
        for v in violations
        if "duplicate" in v or "orphan" in v or "mismatch" in v or "1-to-1" in v
    ]
    if hard_violations:
        raise ValueError(
            f"integrate_standard_layer: {len(hard_violations)} hard integrity "
            f"violation(s) detected (duplicate PK / FK orphan / entry-result 1-to-1 "
            f"mismatch); refusing to write structurally inconsistent corpus. "
            f"First 3: {hard_violations[:3]}"
        )

    # ----- MEDIUM #13: audit_leakage CALLED on merged race + entry -----
    race_leaked = audit_leakage(
        [RaceSchema], merged_race, "post-integration race audit"
    )
    if race_leaked:
        raise ValueError(
            f"integrate_standard_layer: race audit leaked post-race columns "
            f"{race_leaked!r} (race must be pre-race only)"
        )
    entry_leaked = audit_leakage(
        [EntrySchema], merged_entry, "post-integration entry audit"
    )
    # popularity/win_odds are intentionally post-race per Phase 1 D-03 (Harville
    # EV proxy). Any OTHER leak is a hard error.
    expected_entry_leak = {"popularity", "win_odds"}
    unexpected_entry_leak = set(entry_leaked) - expected_entry_leak
    if unexpected_entry_leak:
        raise ValueError(
            f"integrate_standard_layer: entry audit leaked UNEXPECTED post-race "
            f"columns {sorted(unexpected_entry_leak)!r} "
            f"(expected only {sorted(expected_entry_leak)!r})"
        )
    # WR-03 (Phase 06 review): defense-in-depth — confirm the expected leaks
    # ARE present. _assert_column_set_equality (line 279-280) is the primary
    # guard for column presence and would catch a missing column first, but
    # this audit is documented as the last line of defense. If a future
    # refactor weakened the column-set equality check, a silent column drop
    # (e.g. popularity dropped from one input source) would otherwise go
    # undetected here. The expected leaks MUST be in the merged entry columns.
    missing_expected = expected_entry_leak - set(merged_entry.columns)
    if missing_expected:
        raise ValueError(
            f"integrate_standard_layer: entry table is MISSING expected "
            f"post-race columns {sorted(missing_expected)!r} (silent column "
            f"drop — popularity/win_odds must be present per Phase 1 D-03)"
        )

    # ----- HIGH #6 cycle-3 + cycle-5: validate-before-swap with idempotent recovery -----
    staging_dir = Path(
        tempfile.mkdtemp(prefix=".integration_staging_", dir=str(standard_dir))
    )
    try:
        # Stage all 3 merged frames via _atomic_write_parquet. NOTE:
        # _atomic_write_parquet's internal os.replace commits each STAGING file
        # BEFORE the swap loop; these staging commits are NOT routed through
        # _commit_staging and are NOT patched by the cycle-5 transactionality
        # test (which patches _commit_staging directly).
        for table, merged in merged_by_table.items():
            _atomic_write_parquet(merged, staging_dir / f"{table}.parquet")

        # Validate each staged file: row count > 0, schema column-set, PK unique.
        for table, schema in SCHEMA_BY_TABLE.items():
            staged_path = staging_dir / f"{table}.parquet"
            staged = pd.read_parquet(staged_path, engine="pyarrow")
            if len(staged) == 0:
                raise ValueError(
                    f"integrate_standard_layer[{table!r}]: staged file has 0 rows "
                    f"(expected > 0); aborting swap"
                )
            staged_cols = set(staged.columns)
            expected_cols = set(schema.model_fields.keys())
            if staged_cols != expected_cols:
                raise ValueError(
                    f"integrate_standard_layer[{table!r}]: staged column set "
                    f"diverges (extra={sorted(staged_cols - expected_cols)}, "
                    f"missing={sorted(expected_cols - staged_cols)}); aborting swap"
                )
            pk = PK_BY_TABLE[table]
            if pk in staged.columns:
                dup_count = int(staged[pk].duplicated().sum())
                if dup_count > 0:
                    raise ValueError(
                        f"integrate_standard_layer[{table!r}]: staged file has "
                        f"{dup_count} duplicate {pk!r}; aborting swap"
                    )

        # Only AFTER all staged files validate, swap into root via the
        # DEDICATED _commit_staging boundary (cycle-5).
        _commit_staging(staging_dir, standard_dir)
    finally:
        # Best-effort staging cleanup. On success the staging files have been
        # os.replace'd into root, so the staging dir is empty. On failure the
        # staging files remain and should be removed so a future run does not
        # pick them up.
        shutil.rmtree(staging_dir, ignore_errors=True)

    logger.info(
        f"integrate_standard_layer: complete -- wrote race/entry/result to "
        f"{standard_dir!s}"
    )

    return {
        "race": standard_dir / "race.parquet",
        "entry": standard_dir / "entry.parquet",
        "result": standard_dir / "result.parquet",
        "audit": {
            "race": race_leaked,
            "entry": entry_leaked,
        },
    }


__all__ = [
    "integrate_standard_layer",
    "SCHEMA_BY_TABLE",
    "PK_BY_TABLE",
    "_recast_to_canonical",
    "_assert_column_set_equality",
    "_commit_staging",
]
